name: CL

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable RDP and Configure Windows
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
        Restart-Service termservice -Force

    - name: Start Serveo Tunnel for RDP
      run: ssh -T -R 80:localhost:3389 serveo.net

    - name: Simulate Stuck Behavior for 10 Minutes
      run: |
        Write-Host "Simulating stuck tunnel for 10 minutes..."
        Start-Sleep -Seconds 600
