name: RDP Tunnel

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable RDP and Configure Windows
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
        Restart-Service termservice -Force

    - name: Install and Start Localtunnel for RDP
      shell: bash
      run: |
        npm install -g localtunnel
        echo "Starting Localtunnel..."
        lt --port 3389 > localtunnel_output.txt &
        sleep 10  # Give Localtunnel time to establish the tunnel
        cat localtunnel_output.txt  # Output the Localtunnel URL

    - name: Simulate Stuck Behavior for 100 Minutes
      run: |
        Write-Host "Simulating stuck tunnel for 100 minutes..."
        Start-Sleep -Seconds 6000
