name: RDP Tunnel

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable RDP and Configure Windows
      run: |
        # Enable Remote Desktop and configure firewall
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        # Set up RDP user account
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
        Restart-Service termservice -Force

    - name: Start Serveo Tunnel for RDP
      shell: bash
      run: |
        echo "Starting Serveo tunnel..."
        # Start Serveo tunnel in the background
        ssh -o StrictHostKeyChecking=no -T -R 3389:localhost:3389 serveo.net > serveo_output.txt 2>&1 &
        # Keep the process running by waiting indefinitely
        while true; do sleep 60; done

    - name: Output Tunnel URL
      shell: bash
      run: |
        # Output the Serveo tunnel URL from the log file
        cat serveo_output.txt
