name: CL

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable RDP and Configure Windows
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
        Restart-Service termservice -Force

    - name: Start Serveo Tunnel for RDP and Capture Output
      shell: bash
      run: |
        echo "Starting Serveo tunnel..."
        # Automatically accept new host keys
        ssh -o StrictHostKeyChecking=no -T -R 80:localhost:3389 serveo.net > serveo_output.txt &
        sleep 10  # Give Serveo time to establish the tunnel
        cat serveo_output.txt  # Output the Serveo tunnel URL

    - name: Simulate Stuck Behavior for 10 Minutes
      run: |
        Write-Host "Simulating stuck tunnel for 10 minutes..."
        Start-Sleep -Seconds 600
